version: '3'

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      WEATHER_API_ENDPOINT: https://api.openweathermap.org/data/2.5/onecall
      WEATHER_API_KEY: "fake_key"
